server:
  port: 8080
spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /**
  mail:
    host: smtp.qq.com
    username: cydaily@qq.com  #发送方的邮箱
    password: ydsudmeelrggebbj  # 设置密码，该处的密码是发送方QQ邮箱开启SMTP的授权码而非QQ密码
    port: 587
    properties:
      mail:
        stamp:
          ssl:
            trust: smtp.qq.com
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 587
            class: javax.net.ssl.SSLSocketFactory
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auto_submit?characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5

# 回调地址
CALLBACK_URL: https://v2.xiaoyang666.top
# 微信通知TOKEN
APP_TOKEN: AT_sAwyp9Yus1w5TAoQIm2Yy1evNzjKDcQU

LOGIN_API: https://thxy.campusphere.net/iap/
# 是否需要验证码接口，连续三次输错密码智慧校园将会要求输入验证码，防君子不防小人
NEEDCAPTCHA_API:
# 获取验证码接口
CAPTCHA_API: https://thxy.campusphere.net/iap/generateCaptcha
# 获取未填写表单数据
COLLECTING_PROCESSING: https://thxy.campusphere.net/wec-counselor-collector-apps/stu/collector/queryCollectorProcessingList
# 获取表单基本信息
DETAIL_COLLECTOR: https://thxy.campusphere.net/wec-counselor-collector-apps/stu/collector/detailCollector
# 获取表单字段
FROM_FIELD: https://thxy.campusphere.net/wec-counselor-collector-apps/stu/collector/getFormFields
# 提交表单
SUBMIT_FROM: https://thxy.campusphere.net/wec-counselor-collector-apps/stu/collector/submitForm

# ====================================================用户必填项===============================================================
# 学号
USERNAME: xxxxx
# 密码
PASSWORD: xxxxx
# 邮箱通知
EMAIL: xxxxx@qq.com
# 定位地址
ADDRESS: 广州市番禺区番禺广场